# Generated by Django 4.0.1 on 2022-01-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=256)),
                ('hemail', models.EmailField(max_length=254)),
                ('ename', models.CharField(max_length=256)),
                ('eloc', models.CharField(max_length=256)),
                ('edesc', models.TextField()),
                ('sdate', models.DateField()),
                ('stime', models.TimeField()),
                ('edate', models.DateField()),
                ('etime', models.TimeField()),
                ('rdate', models.DateField()),
                ('rtime', models.TimeField()),
            ],
        ),
    ]
