# Generated by Django 4.0.1 on 2022-01-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='edate',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='reg',
            name='etime',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='reg',
            name='rdate',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='reg',
            name='rtime',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='reg',
            name='sdate',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='reg',
            name='stime',
            field=models.CharField(max_length=256),
        ),
    ]
