# Generated by Django 4.0.1 on 2022-01-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_alter_reg_edate_alter_reg_etime_alter_reg_rdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='edate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reg',
            name='etime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reg',
            name='rdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reg',
            name='rtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reg',
            name='sdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reg',
            name='stime',
            field=models.TimeField(),
        ),
    ]
