# Generated by Django 4.0.1 on 2022-01-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_alter_reg_edate_alter_reg_etime_alter_reg_rdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='pswd',
            field=models.CharField(default='pswd', max_length=256),
        ),
    ]
