# Generated by Django 4.0.1 on 2022-01-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_part'),
    ]

    operations = [
        migrations.DeleteModel(
            name='part',
        ),
    ]
