# Generated by Django 4.0.1 on 2022-01-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_delete_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=256)),
                ('lname', models.CharField(max_length=256)),
                ('iemail', models.EmailField(max_length=254)),
                ('icon', models.CharField(max_length=256)),
                ('rno', models.CharField(default='1', max_length=256)),
            ],
        ),
    ]
