# Generated by Django 4.0.1 on 2022-01-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='eid',
            field=models.CharField(default='5', max_length=256),
        ),
    ]
