# Generated by Django 4.0.1 on 2022-01-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0009_alter_part_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='rnog',
            field=models.CharField(default='NULL', max_length=256),
        ),
        migrations.AddField(
            model_name='part',
            name='rnoi',
            field=models.CharField(default='NULL', max_length=256),
        ),
        migrations.AlterField(
            model_name='part',
            name='rno',
            field=models.CharField(max_length=256),
        ),
    ]
