# Generated by Django 4.0.1 on 2022-01-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0010_part_rnog_part_rnoi_alter_part_rno'),
    ]

    operations = [
        migrations.CreateModel(
            name='das',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=256)),
                ('epass', models.CharField(max_length=256)),
            ],
        ),
    ]
