# Generated by Django 4.0.1 on 2022-01-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0011_das'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='rnog',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='part',
            name='rnoi',
            field=models.CharField(max_length=256),
        ),
    ]
