# Generated by Django 4.0.1 on 2022-01-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0013_alter_part_rnog_alter_part_rnoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='pswd',
            field=models.CharField(max_length=256),
        ),
    ]
