# Generated by Django 4.0.1 on 2022-01-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0014_alter_reg_pswd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='rnog',
            new_name='rtpye',
        ),
        migrations.RemoveField(
            model_name='part',
            name='rnoi',
        ),
    ]
