# Generated by Django 4.0.1 on 2022-01-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0015_rename_rnog_part_rtpye_remove_part_rnoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='rno',
            field=models.PositiveIntegerField(max_length=256),
        ),
    ]
