# Generated by Django 4.0.1 on 2022-01-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0017_alter_part_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='icon',
            field=models.CharField(max_length=256),
        ),
    ]
