# Generated by Django 4.0.1 on 2022-01-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0018_alter_part_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='rno',
            field=models.PositiveIntegerField(),
        ),
    ]
