# Generated by Django 4.0.1 on 2022-01-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0019_alter_part_rno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='iemail',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='reg',
            name='hemail',
            field=models.CharField(max_length=256),
        ),
    ]
